### ISSUE TITLE
Simplify command line interface

### ISSUE THREAD

**Issue by rdnfn** [rdnfn/beobench#22]
### Description

Currently calling the command line is a bit unwieldy:

```
python -m beobench.experiment.scheduler
```

This could be replaced with something like:

```
beobench run --method ppo --env boptest.bestest_hydronic_v0
```

### How

Following the [click guide on integrating with Setup tools](https://click.palletsprojects.com/en/8.0.x/setuptools/), use the `entry_points` argument of the `setuptools.setup()` to remove `python -m` from CLI calls.

### TODOs
- [x] Update click command
- [x] Add `env` 
- [x] and `method` args to CLI and Python API
- [x] Fix `no_container` command to work with new CLI
