### ISSUE TITLE
Roadmap: agent/env split

### ISSUE THREAD

**Issue by rdnfn** [rdnfn/beobench#93]
This issue describes the roadmap towards splitting up the agent and environment side of Beobench experiment containers. This improvement was first suggested in #86 by @david-woelfle, big thanks!

### Core functionality

- [x] Create minimal working Celery example (done by @david-woelfle #92)
- [ ] Create minimal Celery example that allows local execution of agent
- [ ] Create minimal Celery example that actually interacts with default OpenAI Gym environment (e.g. cartpole)
- [ ] Create example of Beobench-based environment that is usable via Celery
- [ ] Create automated pipeline to add Celery API to any Beobench experiment container

### Testing

- [ ] Test compatiblity with varying Python/numpy versions

**Comment by david-woelfle** [comment]
You are welcome :)
